#KootPanKing Settings
#Tue Mar 24 00:26:01 KST 2026
alwaysOnTop=true
animInterval=0
app.jsaPath=C\:\\Users\\garpsu\\KootPanKing_Proj\\KootPanKing.jsa
bgImagePath=
borderAlpha=0
borderColor=-15461356
borderVisible=true
borderWidth=20
bubbleMode=false
camera.url=http\://192.168.0.100\:8080
cameraMode=false
chimeDuration=2
chimeEnabled=true
chimeFile=C\:\\Windows\\Media\\Ring08.wav
chimeMinutes=0,30
chimeVolume=80
cityName=Local
clockRadius=230
digFontName=Consolas
digFontSize=14
digitalColor=-1
digitalNoBg=false
fireMode=false
fontName=Georgia
fontSize=14
galaxyMode=false
galaxySpeed=0.004
gmail.from=
gmail.lastTo=
gmail.pass=
hourColor=-14798126
its.cctv.apiKey=5bfd056aa2be4e7fa5a0eb6c76894928
kakao.apiKey=
kakao.clientSecret=
kakao.refreshToken=
mainWindow=false
matrix2Mode=false
matrix2Speed=1.5
matrix3Mode=false
matrix3Speed=1.5
matrixMode=true
matrixSpeed=1.5
minuteColor=-16080866
morningBriefTime=700
naver.caldav.id=
naver.caldav.password=
neonDigital=false
neonMode=true
numberColor=-3355444
opacity=1.0
rainMode=false
rainbowSeconds=30
secondColor=-2351586
secondVisible=true
showDigital=false
showInterval=0
showLunar=false
showNumbers=true
slideEffect=fade
slideEnabled=false
slideFolder=
slideIndex=0
slideInterval=5
slideOverlay=55
snowMode=false
sparkleMode=false
startHidden=false
tg.botToken=
tg.myChatId=
tg.polling=false
theme=Light
tickVisible=true
timeZone=Asia/Seoul
winH=512
winW=512
winX=1124
winY=53
youtubeMode=false
youtubeUrl=https\://www.youtube.com/live/5uZa3-RMFos?si\=OrfrIu4IFmTYojxE
