#KootPanKing Settings
#Sat Mar 21 19:43:24 KST 2026
alwaysOnTop=true
animInterval=0
app.jsaPath=C\:\\Users\\garpsu\\KootPanKingProj\\KootPanKing.jsa
bgColor=-13421569
bgImagePath=
borderAlpha=0
borderColor=-15461356
borderVisible=false
borderWidth=99
bubbleMode=false
camera.url=http\://192.168.0.70\:8080/video
cameraMode=false
chimeDuration=2
chimeEnabled=true
chimeFile=C\:\\Windows\\Media\\Ring08.wav
chimeMinutes=0,15,30,45
chimeVolume=98
cityName=Local
clockRadius=180
digFontName=\uAD74\uB9BC
digFontSize=10
digitalColor=-16777216
digitalNoBg=true
fireMode=false
fontName=Georgia
fontSize=14
galaxyMode=false
galaxySpeed=0.004
gmail.from=
gmail.lastTo=
gmail.pass=
hourColor=-14798126
its.cctv.apiKey=
kakao.apiKey=
kakao.clientSecret=
kakao.refreshToken=
mainWindow=false
matrix2Mode=false
matrix2Speed=1.5
matrix3Mode=false
matrix3Speed=1.5
matrixMode=false
matrixSpeed=1.5
minuteColor=-16080866
morningBriefTime=700
naver.caldav.id=
naver.caldav.password=
neonDigital=false
neonMode=false
numberColor=-6684673
opacity=0.4
rainMode=false
rainbowSeconds=30
secondColor=-2351586
secondVisible=true
showDigital=true
showInterval=0
showLunar=true
showNumbers=true
slideEffect=fade
slideEnabled=false
slideFolder=C\:\\Temp
slideIndex=0
slideInterval=5
slideOverlay=55
snowMode=false
sparkleMode=false
startHidden=false
tg.botToken=
tg.myChatId=
tg.polling=false
theme=Light
tickColor=-3342337
tickVisible=true
timeZone=Asia/Seoul
winH=480
winW=372
winX=1926
winY=203
youtubeMode=false
youtubeUrl=
