#KootPanKing Settings
#Mon Mar 23 16:25:01 KST 2026
alwaysOnTop=true
animInterval=0
app.jsaPath=C\:\\Users\\garpsu\\KootPanKing_Proj\\KootPanKing.jsa
bgColor=-13421569
bgImagePath=
borderAlpha=255
borderVisible=false
borderWidth=-1
bubbleMode=false
camera.url=http\://192.168.0.100\:8080
cameraMode=false
chimeDuration=0
chimeEnabled=false
chimeFile=
chimeMinutes=0
chimeVolume=80
cityName=Local
clockRadius=210
digFontName=Consolas
digFontSize=14
digitalColor=-1
digitalNoBg=false
fireMode=false
fontName=Georgia
fontSize=14
galaxyMode=false
galaxySpeed=0.004
gmail.from=
gmail.lastTo=
gmail.pass=
hourColor=-14798126
its.cctv.apiKey=
kakao.apiKey=
kakao.clientSecret=
kakao.refreshToken=
mainWindow=false
matrix2Mode=false
matrix2Speed=1.5
matrix3Mode=false
matrix3Speed=1.5
matrixMode=false
matrixSpeed=1.5
minuteColor=-16080866
morningBriefTime=700
naver.caldav.id=
naver.caldav.password=
neonDigital=false
neonMode=true
opacity=1.0
rainMode=false
rainbowSeconds=30
secondColor=-2351586
secondVisible=true
showDigital=false
showInterval=0
showLunar=false
showNumbers=false
slideEffect=fade
slideEnabled=false
slideFolder=
slideIndex=0
slideInterval=5
slideOverlay=55
snowMode=false
sparkleMode=false
startHidden=false
tg.botToken=
tg.myChatId=
tg.polling=false
theme=Light
tickVisible=true
timeZone=Asia/Seoul
winH=432
winW=432
winX=1401
winY=46
youtubeMode=false
youtubeUrl=
