## youTubeCctv.ini 
[실시간 / 서울 롯데월드 전망대 뷰]https://www.youtube.com/watch?v=hYGGGLxyB9A
[실시간 / 서울 한강]https://www.youtube.com/watch?v=-JhoMGoAfFc
[실시간 / 서울 남산타워]https://www.youtube.com/watch?v=D-r6_8Iibp8
[실시간 / 부산 광안대교]https://www.youtube.com/watch?v=fWAYIe5-C4o
[실시간 / 서울역]https://www.youtube.com/live/DSgn-lTHJzM?si=fH-q-ngiKPkyfZJ6
[실시간 / 한강공원 올림픽대로 반포대교]https://www.youtube.com/live/m0bJROup7iE?si=e8JfJhO15HeqyouM
[실시간 / 한강 보트장]https://www.youtube.com/live/3Uf3w-UHB4U?si=7ZOc0fLVPB0B1H29
[실시간 / 한강 마포 월드컵대교]https://www.youtube.com/live/ahSMyLJcp48?si=Swlko5ua4CKT5NkB
[실시간 / 제주도 성산 일출봉]https://www.youtube.com/watch?v=1AUCJbyKoMo
[실시간 / 제주도 훑어보기]https://www.youtube.com/watch?v=d07UZ09zDJ8
[실시간 / 서울 광화문4거리]https://www.youtube.com/watch?v=b-nJ9MZ3vNk
[실시간 / 도쿄 시부야]https://www.youtube.com/live/dfVK7ld38Ys?si=EBWwkHUyWom-zIcw
[실시간 / 뉴욕 타임스퀘어]https://www.youtube.com/watch?v=rnXIjl_Rzy4
[실시간 / 샌프란시스코 Bay Bridge]https://www.youtube.com/watch?v=CXYr04BWvmc
[실시간 / 시드니]https://www.youtube.com/live/5uZa3-RMFos?si=OrfrIu4IFmTYojxE
[실시간 / 하와이 와이키키]https://www.youtube.com/watch?v=X0idnu7HUmI
[실시간 / 싱가포르 도심]https://www.youtube.com/watch?v=9cfkyMzanbc
[실시간 / 파리 에펠탑]https://www.youtube.com/watch?v=OzYp4NRZlwQ
[실시간 / 이탈리아 베니스 리알토 다리]https://www.youtube.com/watch?v=K_Vg94nBiaY
[실시간 / 전세계 훑어보기]https://www.youtube.com/watch?v=z7SiAaN4ogw
[실시간 / 유럽 훑어보기]https://www.youtube.com/watch?v=w9ICwT2WZy8
[실시간 / 뉴욕 여신상]https://www.youtube.com/watch?v=3R2wx2Qi3SA
[실시간 / 영국 런던 도심]https://www.youtube.com/watch?v=WKGK_hYnlGE